name: Code

on:
    pull_request:
        branches:
            - master

env:
    BUN_ENV: production
    FORCE_COLOR: 1

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    job:
        name: ${{ matrix.script }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                script: [test, lint, check, format]
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Tools
              uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

            - name: Install
              run: bun install

            - name: Run ${{ matrix.script }}
              run: bun run ${{ matrix.script }}
